<?php

namespace Database\Seeders;

use App\Models\Absen;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Manager Kasus',
            'email' => 'mk@moka.ol',
            'password' => '$2y$10$9BcBcEWaVUmAOrl2zZkaKeYRZaajkbtNFlAcpNTwkXDab9e00kqlq',
            'kantor_latitude' => '-6.190168332129727',
            'kantor_longitude' => '106.90603079940675',
        ]);

        $absen = [
            [
            'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
            'tanggal_masuk' => '2024-12-02',
            'jam_masuk' => '07:38:10',
            'koordinat_masuk' => 'dasd32dwqdasdasdsa',
            'foto_masuk' => 'default.png',
            'catatan_masuk' => NULL,
            'tanggal_pulang' => '2024-12-02',
            'jam_pulang' => '16:30:00',
            'koordinat_pulang' => 'dasd32dwqdasdasdsa',
            'foto_pulang' => 'default.png',
            // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-03',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-03',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-04',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-04',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-05',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-05',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-06',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-06',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-07',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => NULL,
                'jam_pulang' => NULL,
                'koordinat_pulang' => NULL,
                'foto_pulang' => NULL,
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-09',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-09',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-10',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-10',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-11',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-11',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-12',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-02',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-13',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-13',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-16',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-16',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-17',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-17',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-19',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-19',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-23',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-23',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-24',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-24',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-25',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-25',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-27',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-27',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-30',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-30',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ],
            [
                'uuid' => '98283dy8723y8dy28d2h',
                'user_id' => '1',
                'tanggal_masuk' => '2024-12-31',
                'jam_masuk' => '07:38:10',
                'koordinat_masuk' => 'dasd32dwqdasdasdsa',
                'foto_masuk' => 'default.png',
                'catatan_masuk' => NULL,
                'tanggal_pulang' => '2024-12-31',
                'jam_pulang' => '16:30:00',
                'koordinat_pulang' => 'dasd32dwqdasdasdsa',
                'foto_pulang' => 'default.png',
                // 'catatan_pulang ' => NULL,
            ]
        ];
        Absen::insert($absen);
    }
}
